// <auto-generated />
using System;
using CourseApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250101150621_total_upgrade")]
    partial class total_upgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseApp.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41330934-5681-4660-bfd0-a7c91940073f"),
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("8672057e-cd8e-4f23-b002-f1a2785fe8f3"),
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        });
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9beb751f-f3b8-4e45-a938-622ebc1dd038"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ea26e95-9517-48db-96ba-138e1badeb10",
                            Email = "user1@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Ömer Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "OMERYILMAZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEOJKYJ26u9WYWk09Ox/MkjADfyD7XAy99UKY7juafqkpkyLnvpM7WRbWih3BeRs83A==",
                            PhoneNumber = "5551112233",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "omeryilmaz"
                        },
                        new
                        {
                            Id = new Guid("54039b1c-f914-4171-97a8-f78a9c107935"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6faf2bd-e33a-4c8c-821c-0fdd0dacdb27",
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Okan Buruk",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "OKANBURUK",
                            PasswordHash = "AQAAAAIAAYagAAAAEPLEPNVded8aR7+7hvpX6ZC9sTNuQFyc1cqSTERtRPDTrWnhadyD0GhG1Z0hcJFZ/Q==",
                            PhoneNumber = "5552223344",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "okanburuk"
                        },
                        new
                        {
                            Id = new Guid("4f1d809c-9ccf-4479-b1ab-273f6193679b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5bee7a2b-2166-45cf-8164-9bb534ae7070",
                            Email = "user3@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Kıvanç Tatlıtuğ",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "KIVANCTATLI",
                            PasswordHash = "AQAAAAIAAYagAAAAEAQ2MJIdmxppt664W7SYezooWkJZJQyIhLN6h3U+p65TGqT/5GiBILmJuFPOsZrq5Q==",
                            PhoneNumber = "5553334455",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kivanctatli"
                        },
                        new
                        {
                            Id = new Guid("2d8651fd-3800-48da-a85c-f294282b5180"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83f229ee-8eb2-4c84-a059-a130b6149e79",
                            Email = "user4@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Kerem Aktürkoğlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@GMAIL.COM",
                            NormalizedUserName = "KEREMTURK",
                            PasswordHash = "AQAAAAIAAYagAAAAEJqrheVkippD/zxlEJ/zEQ6YaEao8IL0LhZPFGxz+4ZvXbLjF2Q/X7rV13HqayWu5g==",
                            PhoneNumber = "5554445566",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "keremturk"
                        },
                        new
                        {
                            Id = new Guid("32b60a7d-1f1d-4e78-a968-9aa5a3b074d8"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a39ce119-6fab-4c92-85d9-e75ae579fd30",
                            Email = "user5@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Victor Osimhen",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@GMAIL.COM",
                            NormalizedUserName = "OSIMHEN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIjaj8JYQEoj1kqYcJ1zsymEny81BvcbN1LnecUpfE+JzKiMnPpUADAqdLCIdCO/yA==",
                            PhoneNumber = "5555556677",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "osimhen"
                        },
                        new
                        {
                            Id = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d50bfa63-40ec-4bbb-8dd3-21df5ce17675",
                            Email = "teacher1@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Ahmet Kaya",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER1@GMAIL.COM",
                            NormalizedUserName = "AHMETKAYA",
                            PasswordHash = "AQAAAAIAAYagAAAAEH19c68RDy+nTUUoASc+28Z/x7W14ZvzWBLqMrCOAOAOHreshJSDM+wTdbAETKr/Fg==",
                            PhoneNumber = "5556667788",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ahmetkaya"
                        },
                        new
                        {
                            Id = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d3c6ea43-2902-4a6a-b3aa-87d48819a47c",
                            Email = "teacher2@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Fatih Çakıroğlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER2@GMAIL.COM",
                            NormalizedUserName = "FATIHCAMIR",
                            PasswordHash = "AQAAAAIAAYagAAAAEJFgNTraw+MbssmpIp0nnR07TTjJz8IKCeWa4rDgXYgPcbiM2bneIxmxiX67iQdQ/w==",
                            PhoneNumber = "5557778899",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "fatihcakiroglu"
                        },
                        new
                        {
                            Id = new Guid("e0a405f8-b689-4263-afd2-a35314b7e8d9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed4c18e1-c5fd-417d-9df6-bde8b27a13ee",
                            Email = "teacher3@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Şadi Evren Şeker",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER3@GMAIL.COM",
                            NormalizedUserName = "SADIEVRENSEKER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPCtcyGULpOFUyDjj9KY1h19vNgCyDB9lLlLRdoYfC0vUn98smch6AHUa4D7zhgIQg==",
                            PhoneNumber = "5558889900",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "sadievrenseker"
                        });
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(2025, 1, 1, 18, 6, 20, 994, DateTimeKind.Local).AddTicks(2149),
                            Name = "Software"
                        },
                        new
                        {
                            Id = new Guid("a82c256f-6027-4c22-87ca-22fb85c2daf6"),
                            CreatedDate = new DateTime(2025, 1, 1, 18, 6, 20, 994, DateTimeKind.Local).AddTicks(2169),
                            Name = "Design"
                        },
                        new
                        {
                            Id = new Guid("a2308a61-470a-46e9-ba82-87c3090046fb"),
                            CreatedDate = new DateTime(2025, 1, 1, 18, 6, 20, 994, DateTimeKind.Local).AddTicks(2171),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("80853207-5355-434f-8cab-80e3269d54c4"),
                            CreatedDate = new DateTime(2025, 1, 1, 18, 6, 20, 994, DateTimeKind.Local).AddTicks(2173),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("551963a2-879e-45a6-99a6-5eb512b775c0"),
                            CreatedDate = new DateTime(2025, 1, 1, 18, 6, 20, 994, DateTimeKind.Local).AddTicks(2175),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("8b48bba4-8acd-4ff2-b669-f4095c885e90"),
                            CreatedDate = new DateTime(2025, 1, 1, 18, 6, 20, 994, DateTimeKind.Local).AddTicks(2177),
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = new Guid("a93961af-166d-461c-a6db-263c4d48a55d"),
                            CreatedDate = new DateTime(2025, 1, 1, 18, 6, 20, 994, DateTimeKind.Local).AddTicks(2179),
                            Name = "Photography"
                        });
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f16ad2a-473f-47a9-b26d-523e9f9cf805"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This course covers the fundamentals of C# programming, including syntax, classes, and objects.",
                            ImageUrl = "https://code.visualstudio.com/assets/docs/languages/csharp/csharp-hero.png",
                            Name = "Introduction to C# Programming",
                            Price = 99.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Learn the basics of C# programming"
                        },
                        new
                        {
                            Id = new Guid("e7d6ad2a-473f-47a9-b26d-523e9f9cf806"),
                            CategoryId = new Guid("a82c256f-6027-4c22-87ca-22fb85c2daf6"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn the key principles of UI/UX design to create user-friendly and visually appealing designs.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1733306548826-95daff988ae6?q=80&w=1824&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "UI/UX Design Principles",
                            Price = 149.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Master UI/UX design fundamentals"
                        },
                        new
                        {
                            Id = new Guid("cb89ad2a-473f-47a9-b26d-523e9f9cf807"),
                            CategoryId = new Guid("a2308a61-470a-46e9-ba82-87c3090046fb"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This course provides an introduction to digital marketing, covering SEO, social media, and email marketing.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1661425715124-310ec1b49b8a?q=80&w=1882&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Digital Marketing 101",
                            Price = 199.99m,
                            TeacherId = new Guid("e0a405f8-b689-4263-afd2-a35314b7e8d9"),
                            Title = "Learn digital marketing strategies"
                        },
                        new
                        {
                            Id = new Guid("a29eac2a-473f-47a9-b26d-523e9f9cf808"),
                            CategoryId = new Guid("80853207-5355-434f-8cab-80e3269d54c4"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This course covers essential project management techniques and tools for successful project execution.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1726743809701-67e8600f7670?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Project Management Essentials",
                            Price = 119.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Learn to manage projects effectively"
                        },
                        new
                        {
                            Id = new Guid("f45bda6a-473f-47a9-b26d-523e9f9cf809"),
                            CategoryId = new Guid("551963a2-879e-45a6-99a6-5eb512b775c0"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn the basics of personal finance, including budgeting, saving, and investing.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1663100794696-6b7afa02016c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Personal Finance Basics",
                            Price = 79.99m,
                            TeacherId = new Guid("e0a405f8-b689-4263-afd2-a35314b7e8d9"),
                            Title = "Manage your finances effectively"
                        },
                        new
                        {
                            Id = new Guid("d32f93ae-13f3-452f-97c1-0f9dc7c09300"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This course dives into advanced Python topics, including data structures, algorithms, and performance optimization.",
                            ImageUrl = "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Advanced Python Programming",
                            Price = 129.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Master advanced Python concepts"
                        },
                        new
                        {
                            Id = new Guid("78cb6b7a-5b7e-4977-8e91-31cd22f2e442"),
                            CategoryId = new Guid("a82c256f-6027-4c22-87ca-22fb85c2daf6"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover the tools and techniques to create stunning vector designs using Adobe Illustrator.",
                            ImageUrl = "https://images.unsplash.com/photo-1526485797145-514b2fe83749?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Illustrator Essentials",
                            Price = 99.99m,
                            TeacherId = new Guid("e0a405f8-b689-4263-afd2-a35314b7e8d9"),
                            Title = "Learn Adobe Illustrator from scratch"
                        },
                        new
                        {
                            Id = new Guid("1bfc9db7-3433-4b42-9f5c-bf3c01a8099a"),
                            CategoryId = new Guid("a2308a61-470a-46e9-ba82-87c3090046fb"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn the best SEO practices to rank higher in search engine results and attract more traffic.",
                            ImageUrl = "https://images.unsplash.com/photo-1562577309-2592ab84b1bc?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "SEO Mastery",
                            Price = 179.99m,
                            TeacherId = new Guid("e0a405f8-b689-4263-afd2-a35314b7e8d9"),
                            Title = "Boost your website's SEO"
                        },
                        new
                        {
                            Id = new Guid("3bff33b4-2c5e-4c42-8a73-1d7e7c4d99f3"),
                            CategoryId = new Guid("80853207-5355-434f-8cab-80e3269d54c4"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore Agile project management techniques to deliver successful projects on time.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1661765276951-68739fdcb8ea?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Agile Project Management",
                            Price = 149.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Master Agile methodologies"
                        },
                        new
                        {
                            Id = new Guid("7c9e8ba2-2b7d-4e47-87e2-92d8e6f8b6a3"),
                            CategoryId = new Guid("551963a2-879e-45a6-99a6-5eb512b775c0"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Understand the principles of investing and learn how to grow your wealth over time.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1661765276951-68739fdcb8ea?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Investing for Beginners",
                            Price = 89.99m,
                            TeacherId = new Guid("e0a405f8-b689-4263-afd2-a35314b7e8d9"),
                            Title = "Learn the basics of investing"
                        },
                        new
                        {
                            Id = new Guid("5e7f2b9c-b3f5-4c42-9f7e-8b32e2f8d8a7"),
                            CategoryId = new Guid("a93961af-166d-461c-a6db-263c4d48a55d"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn the art of photography, including composition, lighting, and camera settings.",
                            ImageUrl = "https://images.unsplash.com/photo-1524037992922-3a0937719e1d?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Photography Basics",
                            Price = 79.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Capture stunning photos"
                        },
                        new
                        {
                            Id = new Guid("2b9f7e8d-b4f6-4c3d-8c9f-6b23e7d9f3a2"),
                            CategoryId = new Guid("a2308a61-470a-46e9-ba82-87c3090046fb"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn how to create and promote your personal brand to stand out in your industry.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1683543124615-fb42e42c6201?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Personal Branding",
                            Price = 99.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Build your personal brand"
                        },
                        new
                        {
                            Id = new Guid("9c8f7e2d-b4a6-4f9d-8b32-99f7e6f9b3a4"),
                            CategoryId = new Guid("a82c256f-6027-4c22-87ca-22fb85c2daf6"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover the principles of graphic design and how to create eye-catching visuals.",
                            ImageUrl = "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?q=80&w=2074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Graphic Design Fundamentals",
                            Price = 119.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Learn the basics of graphic design"
                        },
                        new
                        {
                            Id = new Guid("b7e6d3c4-2e4f-4c7a-87e6-7d8f9b32c6a5"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn data analysis, visualization, and machine learning basics with Python.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1714618831065-8e8dadd8d3df?q=80&w=1800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Introduction to Data Science",
                            Price = 199.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Explore the world of data science"
                        },
                        new
                        {
                            Id = new Guid("f7d6c9b8-3e7f-4c6b-98f7-7e9d8c4f6a9b"),
                            CategoryId = new Guid("551963a2-879e-45a6-99a6-5eb512b775c0"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master the tools and techniques needed to analyze financial statements and make better decisions.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1661418553375-5ea448f11f34?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Financial Analysis Basics",
                            Price = 149.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Learn financial analysis techniques"
                        },
                        new
                        {
                            Id = new Guid("b6c8e7d9-2e4b-4c3f-98f7-7e6b9c4a9d8f"),
                            CategoryId = new Guid("8b48bba4-8acd-4ff2-b669-f4095c885e90"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn the skills needed to speak confidently and effectively in front of an audience.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1661780400751-e8e9a09ba7b1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Public Speaking Confidence",
                            Price = 89.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Speak confidently in public"
                        },
                        new
                        {
                            Id = new Guid("8b6c9d7e-2f4b-47a6-87e6-7b9c4f6a9d3e"),
                            CategoryId = new Guid("8b48bba4-8acd-4ff2-b669-f4095c885e90"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn how to craft compelling stories and improve your writing skills.",
                            ImageUrl = "https://images.unsplash.com/photo-1617575521317-d2974f3b56d2?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Creative Writing",
                            Price = 109.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Master the art of storytelling"
                        },
                        new
                        {
                            Id = new Guid("9f3c8e7b-2d4e-4c7a-87f7-7b9d8c4f6a9e"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn to build responsive and interactive web pages using modern frontend technologies.",
                            ImageUrl = "https://images.unsplash.com/photo-1508317469940-e3de49ba902e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Frontend Development Essentials",
                            Price = 129.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Master HTML, CSS, and JavaScript"
                        },
                        new
                        {
                            Id = new Guid("9b6d7e3c-2e4f-48a7-9c3b-7e9f8d4c6a7e"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn to create 2D and 3D games using the Unity engine and C# scripting.",
                            ImageUrl = "https://cdn.prod.website-files.com/618d852d383de946ce0e3fa5/621675c05eb08a490b32f9f1_image%2B(1)%20(1).webp",
                            Name = "Unity Game Development",
                            Price = 149.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Build games with Unity"
                        },
                        new
                        {
                            Id = new Guid("a2c4d9b8-3e4f-47a6-98f7-7d6c9f8e4a7b"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn to create high-performance web APIs and applications using .NET Core.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5rxZLdUPpgRio9Nt-sqVL7hjxmk0xoGU0dQ&s",
                            Name = ".NET Core Development",
                            Price = 159.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Master .NET Core and build robust APIs"
                        },
                        new
                        {
                            Id = new Guid("1d9a5bcd-2390-4f8e-92c3-d23a5bcd2391"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn React, Angular, and Vue.js to build complex and interactive web applications.",
                            ImageUrl = "https://images.unsplash.com/photo-1508317469940-e3de49ba902e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Advanced Frontend Development",
                            Price = 149.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Master advanced frontend technologies"
                        },
                        new
                        {
                            Id = new Guid("2d8b5cfa-3441-4b9a-832b-d23a6c9d1342"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn advanced techniques for 3D game development, including physics and AI integration in Unity.",
                            ImageUrl = "https://cdn.prod.website-files.com/618d852d383de946ce0e3fa5/621675c05eb08a490b32f9f1_image%2B(1)%20(1).webp",
                            Name = "Unity Advanced Game Mechanics",
                            Price = 199.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Master advanced Unity game development"
                        },
                        new
                        {
                            Id = new Guid("3e7c5dfb-7892-4c9a-913b-e45b8c9d1343"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn how to design and build responsive websites using CSS, Flexbox, and Grid Layout.",
                            ImageUrl = "https://images.unsplash.com/photo-1508317469940-e3de49ba902e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Responsive Web Design",
                            Price = 129.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Create beautiful responsive websites"
                        },
                        new
                        {
                            Id = new Guid("4f6d7cfb-6783-4d9a-91b4-f56d8c9d1344"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn JavaScript from scratch, including variables, functions, and DOM manipulation.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a4/JavaScript_code.png",
                            Name = "JavaScript for Beginners",
                            Price = 89.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Master the fundamentals of JavaScript"
                        },
                        new
                        {
                            Id = new Guid("5f7e8cfb-8914-4e9a-92c5-167e9d9d1345"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master complex CSS concepts like animations, transitions, and preprocessors like SASS and LESS.",
                            ImageUrl = "https://cdn.prod.website-files.com/6097e0eca1e875de53031ff6/66b344b75c2572d16bb65242_66b343c191fd4cea42793a3a_image%2520-%25202024-08-07T125129.064.png",
                            Name = "CSS Mastery",
                            Price = 109.99m,
                            TeacherId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            Title = "Advanced CSS techniques"
                        },
                        new
                        {
                            Id = new Guid("fc8dca73-6833-4d5f-9c76-73e7fd8ce9d4"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master advanced .NET Core features to develop scalable and secure backend applications.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5rxZLdUPpgRio9Nt-sqVL7hjxmk0xoGU0dQ&s",
                            Name = "Advanced .NET Backend Development",
                            Price = 159.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Build enterprise-level backend systems"
                        },
                        new
                        {
                            Id = new Guid("4bced12f-c5b0-484d-8fd6-a9557329b1e0"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn how to build, secure, and optimize APIs using .NET Core.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5rxZLdUPpgRio9Nt-sqVL7hjxmk0xoGU0dQ&s",
                            Name = "Building APIs with .NET Core",
                            Price = 139.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Create robust and efficient APIs"
                        },
                        new
                        {
                            Id = new Guid("b71f2993-7de5-4175-8421-875eb7323b5a"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn advanced techniques for working with databases using Entity Framework Core.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5rxZLdUPpgRio9Nt-sqVL7hjxmk0xoGU0dQ&s",
                            Name = "Entity Framework Core Mastery",
                            Price = 149.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Master data access with EF Core"
                        },
                        new
                        {
                            Id = new Guid("2dea5bce-36b6-457a-9a31-4626f9b213ec"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn to implement robust security practices in ASP.NET Core applications.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5rxZLdUPpgRio9Nt-sqVL7hjxmk0xoGU0dQ&s",
                            Name = "ASP.NET Core Security",
                            Price = 169.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Secure your web applications"
                        },
                        new
                        {
                            Id = new Guid("24eb5fb1-e5cb-4318-8612-ef01d60a09ef"),
                            CategoryId = new Guid("4290c1e9-2c24-45d1-8d7b-35482a001044"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master microservices development and deployment with .NET and Docker.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5rxZLdUPpgRio9Nt-sqVL7hjxmk0xoGU0dQ&s",
                            Name = "Microservices with .NET",
                            Price = 189.99m,
                            TeacherId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            Title = "Develop microservices architecture"
                        });
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ThreeDSStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("9beb751f-f3b8-4e45-a938-622ebc1dd038"),
                            RoleId = new Guid("41330934-5681-4660-bfd0-a7c91940073f")
                        },
                        new
                        {
                            UserId = new Guid("54039b1c-f914-4171-97a8-f78a9c107935"),
                            RoleId = new Guid("41330934-5681-4660-bfd0-a7c91940073f")
                        },
                        new
                        {
                            UserId = new Guid("4f1d809c-9ccf-4479-b1ab-273f6193679b"),
                            RoleId = new Guid("41330934-5681-4660-bfd0-a7c91940073f")
                        },
                        new
                        {
                            UserId = new Guid("2d8651fd-3800-48da-a85c-f294282b5180"),
                            RoleId = new Guid("41330934-5681-4660-bfd0-a7c91940073f")
                        },
                        new
                        {
                            UserId = new Guid("32b60a7d-1f1d-4e78-a968-9aa5a3b074d8"),
                            RoleId = new Guid("41330934-5681-4660-bfd0-a7c91940073f")
                        },
                        new
                        {
                            UserId = new Guid("3e28d8c3-d490-4aaa-ad29-fb93c8e99c27"),
                            RoleId = new Guid("8672057e-cd8e-4f23-b002-f1a2785fe8f3")
                        },
                        new
                        {
                            UserId = new Guid("a87cdd8b-274d-4334-8528-979ac1f420a9"),
                            RoleId = new Guid("8672057e-cd8e-4f23-b002-f1a2785fe8f3")
                        },
                        new
                        {
                            UserId = new Guid("e0a405f8-b689-4263-afd2-a35314b7e8d9"),
                            RoleId = new Guid("8672057e-cd8e-4f23-b002-f1a2785fe8f3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Course", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseApp.Domain.Entities.AppUser", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Category");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Order", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.Course", "Course")
                        .WithMany("Orders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseApp.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Payment", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("CourseApp.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseApp.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CourseApp.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Course", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CourseApp.Domain.Entities.Order", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
